[package]
name = "slog-loggly"
version = "0.3.2"
edition = "2018"
authors = ["Angelcam, Inc."]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/angelcam/rust-slog-loggly"
documentation = "https://docs.rs/slog-loggly"
homepage = "https://github.com/angelcam/rust-slog-loggly"
description = """
This is an unofficial Loggly drain for the slog logging infrastructure in Rust.
"""
categories = ["development-tools::debugging"]
keywords = ["logging", "slog", "loggly"]

[features]
default = ["runtime"]
runtime = ["tokio"]

[dependencies]
bytes        = "0.4"
chrono       = "0.4"
erased-serde = "0.3"
futures      = "0.1"
hyper        = "0.12"
hyper-rustls = "0.17.1"
serde        = "1.0"
serde_json   = "1.0"
tokio-timer  = "0.2.6"

[dependencies.tokio]
version  = "0.1"
optional = true

[dependencies.slog]
version = "2.3"
features = ["nested-values"]

[dev-dependencies]
tokio = "0.1"
slog_derive = "0.1"
serde = {version = "1.0", features = ["derive"]}

[[example]]
name = "log"
required-features = ["runtime"]

[[example]]
name = "nested"
